# Candidate Text Description Set
ucm_candidate_descriptions = [
    "A satellite image of agricultural fields showing rows of crops and patches of farmland.",
    "A satellite image of an airplane, possibly on a runway or parked at an airport",
    "A satellite image of a baseballdiamond with a clearly visible infield and outfield",
    "A satellite image of a sandy beach along a coastline, with waves and possibly some beachgoers",
    "A satellite image of urban buildings, showcasing rooftops and city structures",
    "A satellite image of chaparral vegetation, featuring dense shrubs and dry landscapes",
    "A satellite image of a denseresidential area with closely packed houses",
    "A satellite image of a dense forest with trees covering a large area",
    "A satellite image of a freeway with multiple lanes and vehicles in motion",
    "A satellite image of a golfcourse with green fairways, sand traps, and possibly golfers",
    "A satellite image of a harbor with boats docked and water surrounding the area",
    "A satellite image of a road intersection with crossing streets and vehicles",
    "A satellite image of a mediumdensityresidential area with houses and some open spaces",
    "A satellite image of a mobilehomepark with rows of trailers and small lots",
    "A satellite image of an overpass or bridge crossing over a road or railway",
    "A satellite image of a parkinglot filled with parked cars and marked spaces",
    "A satellite image of a river winding through a landscape, possibly with surrounding vegetation",
    "A satellite image of an airport runway with planes or markings visible",
    "A satellite image of a sparseresidential area with scattered houses.",
    "A satellite image of storage tanks, possibly for oil or water, in an industrial area",
    "A satellite image of a tennis court with clear lines and possibly players"
]

rsi_cb256_descriptions = [
    "A satellite image of cloud formations, showing fluffy, white, and scattered clouds over the landscape.",
    "A satellite image of a desert region, featuring sandy textures, dunes, and barren, arid terrain.",
    "A satellite image of a greenarea covered with dense vegetation, forests, grasslands, and patches of cultivated land.",
    "A satellite image of water bodies, including rivers, lakes, oceans, or reservoirs with visible blue surfaces."
]

rs_image_descriptions = [
    "A satellite image of farmland, displaying cultivated plots, farm boundaries, and crop patterns.",
    "A satellite image of a forest area, filled with dense tree cover and natural green vegetation.",
    "A satellite image of grassland with large open meadows, scattered bushes, and grassy textures.",
    "A satellite image of an industry zone, showing manufacturing plants, storage buildings, and industrial yards.",
    "A satellite image of a parkinglot, packed with vehicles and neatly arranged parking lines.",
    "A satellite image of a resident area, highlighting neighborhoods, houses, and residential blocks.",
    "A satellite image of a river, showing winding water channels cutting through the terrain."
]

aid_candidate_descriptions = [
    "A satellite image of an airport, showing long runways, aircrafts parked on aprons, terminal buildings, and surrounding tarmac areas.",
    "A satellite image of bareland, featuring large patches of exposed soil, dry terrain, minimal vegetation, and natural or cleared earth textures.",
    "A satellite image of a baseball field, with a circular or diamond-shaped infield, an outfield, visible bases, and surrounding spectator stands.",
    "A satellite image of a sandy beach along a coastline, featuring light-colored sand, ocean waves, and possibly beach umbrellas or visitors.",
    "A satellite image of a bridge crossing over water or roadways, displaying structural supports, shadows on the surface below, and connecting transportation routes.",
    "A satellite image of a city center, featuring high-density buildings, commercial blocks, intersecting roads, and a grid-like street layout.",
    "A satellite image of a church, typically characterized by a cross-shaped or rectangular roof layout, a tall steeple or tower, and adjacent open grounds or graveyards.",
    "A satellite image of a commercial area, showcasing retail stores, shopping centers, parking lots, and grid-patterned streets.",
    "A satellite image of a dense residential area, with clusters of closely packed houses or apartment blocks, narrow roads, and little open space.",
    "A satellite image of a desert, characterized by vast sandy or rocky terrain, dune formations, and extremely sparse vegetation.",
    "A satellite image of farmland, showing geometric field patterns, crop rows, irrigation paths, and occasional farm buildings.",
    "A satellite image of a forest, displaying dense tree canopies, dark green textures, and sometimes irregular patterns of clearings or roads cutting through.",
    "A satellite image of an industrial area, featuring large rectangular buildings, storage facilities, smoke stacks, and complex road networks inside the compound.",
    "A satellite image of a meadow, presenting open grass-covered fields, scattered shrubs, and bright green textures without dense tree cover.",
    "A satellite image of a medium-density residential area, showing houses with moderate spacing, yards or gardens, and paved access roads.",
    "A satellite image of a mountain region, with rugged peaks, varying elevations, exposed rock textures, and possible snow cover at higher altitudes.",
    "A satellite image of a park, showing open green spaces, walking trails, scattered trees, and occasionally playgrounds or ponds.",
    "A satellite image of a parking area, filled with neatly arranged vehicles, clearly marked white parking lines, and sometimes shadow patterns of the cars.",
    "A satellite image of a playground, featuring sports courts, open playing fields, playground equipment, and surrounding green or paved areas.",
    "A satellite image of a pond, showing a small body of still water, usually surrounded by vegetation or land, sometimes circular or irregular in shape.",
    "A satellite image of a port, with piers extending into water, docked cargo ships, cranes for loading and unloading containers, and adjacent storage areas.",
    "A satellite image of a railway station, showing train platforms, parallel railway tracks, station buildings, and incoming or outgoing trains.",
    "A satellite image of a resort, including hotel complexes, swimming pools, landscaped gardens, and pathways for relaxation or recreation.",
    "A satellite image of a river, showing a winding water channel, riverbanks lined with vegetation, and bridges or crossings in some areas.",
    "A satellite image of a school, featuring classroom buildings, playgrounds, sports fields, and clear geometric layout.",
    "A satellite image of a sparse residential area, where houses are scattered with large open spaces or natural land in between.",
    "A satellite image of a square, with open paved surfaces, pedestrian paths, monuments or sculptures at the center, and surrounding buildings.",
    "A satellite image of a stadium, displaying a large oval or circular structure, a central sports field, seating areas, and large parking lots nearby.",
    "A satellite image of storage tanks, featuring circular or cylindrical tanks, often in groups, located within an industrial facility or near ports.",
    "A satellite image of a viaduct, showing elevated roads or railways supported by columns, casting long shadows across terrain or lower structures."
]

siri_candidate_descriptions = [
    "A satellite image of agricultural fields showing rows of crops, patches of farmland, and irrigation patterns.",
    "A satellite image of a commercial area with large buildings, parking lots, and grid-like streets for retail and business activities.",
    "A satellite image of a harbor with boats docked along piers, surrounded by water and industrial facilities.",
    "A satellite image of idle land, featuring open soil patches, sparse vegetation, and undeveloped empty spaces.",
    "A satellite image of an industrial area with warehouses, storage tanks, chimneys, and surrounding transportation infrastructure.",
    "A satellite image of a meadow, featuring wide open grassland, scattered shrubs, and smooth green textures.",
    "A satellite image of an overpass or bridge structure crossing over roads or railways, showing shadows and support columns.",
    "A satellite image of a park with open green spaces, walking paths, scattered trees, and recreational areas.",
    "A satellite image of a pond, showing a small enclosed body of still water surrounded by vegetation or bare land.",
    "A satellite image of a residential area with rows of houses, apartment buildings, and winding streets or driveways.",
    "A satellite image of a river meandering through the landscape, with flowing water and vegetated riverbanks.",
    "A satellite image of a water body, such as a lake or large pond, with clear water surfaces and possibly surrounding natural terrain."
]

hellors_candidate_descriptions = [
    "A satellite image of a water body, showing clear surfaces of water such as lakes, reservoirs, or ponds.",
    "A satellite image of a dense forest, featuring large areas covered by trees and thick green vegetation.",
    "A satellite image of cultivateland with rows of crops, patches of farmland, and irrigation structures.",
    "A satellite image of a river winding through the landscape, with flowing water and vegetated riverbanks.",
    "A satellite image of a highway with multiple lanes, vehicles, road markings, and nearby infrastructure.",
    "A satellite image of a pylon, showing tall electrical towers and transmission lines crossing open areas.",
    "A satellite image of a swimmingpool with rectangular or circular shapes, blue water, and surrounding pavements.",
    "A satellite image of a tenniscourt with clear white lines, nets, and a distinct rectangular green or blue surface.",
    "A satellite image of a basketballcourt, showing visible court markings, hoops, and surrounding open spaces.",
    "A satellite image of a footballfield, displaying a large green field with goalposts and white boundary lines."
]

nwpu_resisc45_candidate_descriptions = [
    "A satellite image of an airplane, possibly on a runway or parked at an airport.",
    "A satellite image of an airport with runways, taxiways, and aircraft parking areas.",
    "A satellite image of a baseball diamond with a clearly visible infield and outfield layout.",
    "A satellite image of a basketball court with visible court markings, hoops, and playing areas.",
    "A satellite image of a sandy beach along the coastline, with visible waves and possibly beachgoers.",
    "A satellite image of a bridge spanning over water, roads, or valleys, showing structural details.",
    "A satellite image of chaparral vegetation, featuring dense shrubs and dry brush-covered landscapes.",
    "A satellite image of a church, typically identifiable by cross-shaped structures or steeples.",
    "A satellite image of circular farmland with visible irrigation patterns and green crop circles.",
    "A satellite image of cloud cover partially or fully obscuring the terrain below.",
    "A satellite image of a commercial area, featuring large buildings, shopping centers, and parking lots.",
    "A satellite image of a dense residential area with tightly packed houses and complex street grids.",
    "A satellite image of a desert, featuring vast barren land, dunes, and minimal vegetation.",
    "A satellite image of a forest, showing dense tree coverage and varying green tones.",
    "A satellite image of a freeway with multiple lanes, moving vehicles, and exit ramps.",
    "A satellite image of a golf course, with fairways, greens, sand traps, and water hazards.",
    "A satellite image of a ground track field, with oval-shaped running tracks and athletic markings.",
    "A satellite image of a harbor with boats, docks, piers, and surrounding water areas.",
    "A satellite image of an industrial area with factories, warehouses, and machinery installations.",
    "A satellite image of a road intersection where two or more streets cross, including vehicles and traffic signs.",
    "A satellite image of an island, surrounded by water and sometimes featuring vegetation or rocky terrain.",
    "A satellite image of a lake, a large body of water surrounded by land, reflecting sky and nearby terrain.",
    "A satellite image of a meadow with open grassland and scattered shrubs or wildflowers.",
    "A satellite image of a medium density residential area with detached houses and open yards.",
    "A satellite image of a mobile home park with aligned trailers and small private lots.",
    "A satellite image of a mountain, showing rugged terrain, peaks, and shadows from elevated slopes.",
    "A satellite image of an overpass or bridge, crossing over a highway or railway line.",
    "A satellite image of a palace, showing large-scale architectural buildings, courtyards, and gardens.",
    "A satellite image of a parking lot filled with parked cars and clearly marked parking spaces.",
    "A satellite image of a railway with parallel tracks running through the landscape.",
    "A satellite image of a railway station with platforms, waiting areas, and visible rail tracks.",
    "A satellite image of rectangular farmland, showing large rectangular patches of cultivated land.",
    "A satellite image of a river winding through the terrain, bordered by natural vegetation.",
    "A satellite image of a roundabout with circular traffic flow and landscaped center islands.",
    "A satellite image of a runway, typically part of an airport, featuring straight paved strips and markings.",
    "A satellite image of sea ice, showing frozen ocean surfaces with visible cracks and texture.",
    "A satellite image of a ship sailing on water, showing a visible hull and wake patterns.",
    "A satellite image of a snowberg, a large block of ice or snow, possibly surrounded by water.",
    "A satellite image of a sparse residential area with scattered houses and open undeveloped land.",
    "A satellite image of a stadium, featuring an oval or circular shape with seats and a central field.",
    "A satellite image of storage tanks, often located in industrial areas and used for liquid storage.",
    "A satellite image of a tennis court with clear white lines, a net, and a rectangular green or blue surface.",
    "A satellite image of a terrace, showing stepped agricultural fields built on sloped terrain.",
    "A satellite image of a thermal power station, showing chimneys, cooling towers, and power plant buildings.",
    "A satellite image of a wetland with water-saturated soil, marsh vegetation, and shallow ponds."
]

whu_rs19_candidate_descriptions = [
    "A satellite image of an airport with visible runways, taxiways, terminals, and aircraft.",
    "A satellite image of a sandy beach along the coastline, with visible waves and possibly beachgoers.",
    "A satellite image of a bridge spanning over water, valleys, or roads, showing structural design.",
    "A satellite image of a commercial area with large buildings, stores, and organized parking spaces.",
    "A satellite image of a desert landscape, showing bare sandy surfaces with little or no vegetation.",
    "A satellite image of farmland, showing cultivated fields with visible crop patterns or plowed soil.",
    "A satellite image of a football field with visible goalposts, turf markings, and rectangular layout.",
    "A satellite image of a forest, with dense tree cover and large green canopy areas.",
    "A satellite image of an industrial area with factories, warehouses, and machinery infrastructure.",
    "A satellite image of a meadow with open grassland, wildflowers, and minimal tree coverage.",
    "A satellite image of a mountain, featuring rugged terrain, rocky peaks, and shadowed slopes.",
    "A satellite image of a park with open green spaces, pathways, scattered trees, and recreational zones.",
    "A satellite image of a parking lot with parked cars and clearly marked parking spaces.",
    "A satellite image of a pond, a small water body often surrounded by vegetation and open land.",
    "A satellite image of a port or harbor area, with boats, piers, shipping containers, and dock facilities.",
    "A satellite image of a railway station with visible tracks, platforms, and surrounding buildings.",
    "A satellite image of a residential area with houses, streets, and organized neighborhood layouts.",
    "A satellite image of a river winding through a landscape, surrounded by natural vegetation or urban areas.",
    "A satellite image of a viaduct or elevated road, showing the long bridge structure crossing over terrain or water."
]

patternnet_candidate_descriptions = [
    "A satellite image of an airplane, possibly on a runway or parked at an airport.",
    "A satellite image of a baseball field with a clearly visible diamond, infield, and outfield.",
    "A satellite image of a basketball court with marked lines, hoops, and surrounding paved areas.",
    "A satellite image of a sandy beach along the coastline, featuring waves and beachgoers.",
    "A satellite image of a bridge spanning over water, roads, or valleys, showing its structure.",
    "A satellite image of a cemetery with rows of headstones, pathways, and trees.",
    "A satellite image of chaparral vegetation, featuring dense shrubs and dry landscapes.",
    "A satellite image of a Christmas tree farm with evenly spaced rows of coniferous trees.",
    "A satellite image of a closed road, featuring blocked access points and barriers.",
    "A satellite image of a coastal mansion with large houses located along the shoreline.",
    "A satellite image of a crosswalk showing white pedestrian lines across a road intersection.",
    "A satellite image of a dense residential area with closely packed houses and streets.",
    "A satellite image of a ferry terminal with docks, ferries, and boarding areas near the shoreline.",
    "A satellite image of a football field with clear field markings, goalposts, and stadium surroundings.",
    "A satellite image of a forest with dense tree coverage over a large area.",
    "A satellite image of a freeway with multiple traffic lanes, vehicles, and interchanges.",
    "A satellite image of a golf course with green fairways, sand traps, and possibly players.",
    "A satellite image of a harbor with boats docked and water surrounding piers and shipping areas.",
    "A satellite image of an intersection with crossing roads, traffic markings, and vehicles.",
    "A satellite image of a mobile home park with rows of trailers and organized lots.",
    "A satellite image of a nursing home with buildings, courtyards, and surrounding green areas.",
    "A satellite image of an oil and gas field, showing drilling pads, storage tanks, and pipelines.",
    "A satellite image of an oil well with visible pump jacks and drilling equipment on the site.",
    "A satellite image of an overpass, featuring a raised road or bridge structure crossing another road.",
    "A satellite image of a parking lot with multiple parked vehicles and marked parking spaces.",
    "A satellite image of a parking space showing individual vehicle slots and surrounding infrastructure.",
    "A satellite image of a railway with visible train tracks running through various landscapes.",
    "A satellite image of a river winding through natural or urban areas, surrounded by vegetation or infrastructure.",
    "A satellite image of a runway at an airport, with visible markings and aircraft nearby.",
    "A satellite image of runway markings, featuring white painted guidance lines and signs on the pavement.",
    "A satellite image of a shipping yard with containers, cranes, and ships docked nearby.",
    "A satellite image of a solar panel field with rows of photovoltaic panels arranged systematically.",
    "A satellite image of a sparse residential area with scattered houses and open land spaces.",
    "A satellite image of storage tanks, possibly for oil, gas, or water, typically in an industrial area.",
    "A satellite image of a swimming pool, often rectangular or circular, located in residential or recreational areas.",
    "A satellite image of a tennis court with clear lines, nets, and fenced surroundings.",
    "A satellite image of a transformer station with electrical transformers, towers, and power lines.",
    "A satellite image of a wastewater treatment plant with circular sedimentation tanks and complex pipe layouts."
]

rsc11_candidate_descriptions = [
    "A satellite image of a denseforest with thick tree coverage and minimal open ground.",
    "A satellite image of a grassland featuring large open areas covered with green grass and few trees.",
    "A satellite image of a harbor with boats docked, piers, and water surrounding the area.",
    "A satellite image of highbuildings showcasing tall urban structures and dense city layouts.",
    "A satellite image of lowbuildings with small-scale houses and short rooftops scattered across the area.",
    "A satellite image of an overpass showing a raised road structure crossing over other roads or railways.",
    "A satellite image of a railway with visible parallel train tracks cutting through the landscape.",
    "A satellite image of a residentialarea with clusters of houses, roads, and urban infrastructure.",
    "A satellite image of roads connecting various parts of a city, showing lanes and vehicles in motion.",
    "A satellite image of a sparseforest with widely spaced trees and visible open ground between them.",
    "A satellite image of stroagetanks, usually large circular or cylindrical containers in an industrial zone."
]

dlrsd_candidate_descriptions = [
    "A satellite image of an airplane, possibly on a runway or parked at an airport.",
    "A satellite image of baresoil showing exposed earth surfaces without vegetation or buildings.",
    "A satellite image of buildings, showcasing urban structures, rooftops, and city blocks.",
    "A satellite image of cars parked in lots or moving along roads and highways.",
    "A satellite image of chaparral vegetation, featuring dense shrubs and dry landscapes.",
    "A satellite image of a court, such as a tennis or basketball court, with clear boundary lines.",
    "A satellite image of a dock area with piers extending into the water and boats moored.",
    "A satellite image of a field covered in vegetation or crops, showing rectangular or irregular plots.",
    "A satellite image of grass-covered landscapes with green open areas and minimal structures.",
    "A satellite image of a mobilehome area with rows of trailers and compact housing units.",
    "A satellite image of pavement areas including roads, walkways, and paved urban surfaces.",
    "A satellite image of sand dunes, beaches, or sandy terrain with light-colored textures.",
    "A satellite image of the sea, with visible waves and large open bodies of water.",
    "A satellite image of a ship floating on the sea or docked at a port.",
    "A satellite image of tanks, usually large circular or cylindrical storage containers in industrial areas.",
    "A satellite image of trees, forming dense or sparse forested regions with visible canopies.",
    "A satellite image of water bodies such as lakes, rivers, ponds, or coastal areas."
]
